name: Build and Upload Conda Package

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build Conda Package
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          activate-environment: build-env
          python-version: "3.13"
          use-mamba: true

      - name: Install dependencies
        shell: pwsh
        run: |
          conda install -y conda-build anaconda-client conda-forge::python-libarchive-c conda-forge::libarchive

      - name: Build all recipes
        shell: cmd
        run: |
          for /d %%d in (recipes\*) do conda build "%%d" --output-folder build_artifacts --no-test --no-build-id

      - name: Upload to Anaconda.org
        if: startsWith(github.ref, 'refs/heads/main')
        shell: pwsh
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          Get-ChildItem build_artifacts -Recurse -Filter *.tar.bz2 | ForEach-Object {
              anaconda upload $_.FullName --user biowindows --label main
          }
