name: Build and upload conda packages

on:
  push:
    branches:
      - main

jobs:
  conda_deployment:
    name: Conda deployment
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd /C CALL
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.13
          environment-file: environment.yml
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@v1.4.0
        with:
          meta_yaml_dir: recipes/muscle
          user: biowindows
          token: ${{ secrets.ANACONDA_TOKEN }}
          upload: true
          python-version: 3.13
