name: Build and upload Conda package (manual)

on:
  push:
    branches:
      - main

jobs:
  conda_build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd /C call {0}

    steps:
      - name: ğŸ§¾ Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ§° Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: biowindows
          environment-file: environment.yml
        run: >-
          conda info && conda list
      # - name: ğŸ§ª Create build environment
      #   run: |
      #     conda install -y conda-build anaconda-client conda-forge::python-libarchive-c conda-forge::libarchive
      #     conda info
      #     conda list

      # - name: ğŸ—ï¸ Build Conda package
      #   run: |
      #     echo Building muscle...
      #     conda build recipes/muscle --output-folder build_output
      #     echo Listing build_output contents:
      #     dir build_output

      # - name: â˜ï¸ Upload to Anaconda
      #   env:
      #     ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      #   run: |
      #     echo Uploading package to Anaconda...
      #     for /r build_output %%F in (*.tar.bz2) do (
      #       echo Uploading %%F
      #       anaconda upload --user biowindows "%%F" --label main --force
      #     )
