name: Build and Upload Conda Package

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build Conda Package
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          activate-environment: build-env
          python-version: "3.13"
          use-mamba: true

      - name: Install dependencies
        shell: cmd
        run: |
          conda install -y conda-build anaconda-client conda-forge::python-libarchive-c conda-forge::libarchive

      - name: Build all recipes
        shell: pwsh
        run: |
          Get-ChildItem recipes -Directory | ForEach-Object {
              conda build $_.FullName --output-folder build_artifacts --no-test --no-build-id
          }

      - name: Upload to Anaconda.org
        if: startsWith(github.ref, 'refs/heads/main')
        shell: cmd
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          anaconda upload build_artifacts\**\*.tar.bz2 --user biowindows --label main
